### PR TITLE
aktualizr: switch to 2020.6+fio

### PR DESCRIPTION
**Pull request by mike-sul**
- switch to 2020.6+fio
- adjust implementation to changes in ImageRepository interface

### CODE REVIEW

**Comment by doanac** [comment]
I'm going to review tonight.

**Comment by doanac** [comment]
looks fine. I'm pulling into my factory and doing a little testing tonight

**Comment by mike-sul** [comment]
tested it in my factory, looks fine.

**Comment by doanac** [comment]
Here's my notes:

# Test Plan Used

## Test aktualizr-get
**Run:**
~~~
LOG_STDERR=1 ./aktualizr-get -u https://ota-lite.foundries.io:8443/hub-creds/ 2>/dev/null
~~~
**Expect:** JSON output (stderr shouldn’t show up)

## Test check-in and server update
 1. Look at "last seen" value of `fioctl devices show rpi3-1`
 1. Run: `aktualizr-lite list`
    * Verify proper targets are listed
 1. Repeat step 1 and ensure timestamp has changed

## Test Update Mechanics
 1. Pushed container change
 1. Daemon appies update
 1. `fioctl devices updates list rpi3-1`. shows update
 1. `fioctl devices updates show rpi3-1 <update>`.  Shows things in progress and eventually "complete"
 1. Ensure containers are running for this target (proper hashes etc)
 1. Device gateway testing is execute `fioctl targets tests <target num>`

## Test System and Hardware Info
Run: 
~~~
./aktualizr-lite daemon --loglevel 0  2>&1 | tee /tmp/tmp.log
~~~
and then look for calls to /system_info for network and hardware to succeed.

## Failure Testing
 1. Stop aktualizr-lite daemon
 1. Add a bogus entry for ota-lite.foundries.io into /etc/hosts like:
    * 192.168.0.122 ota-lite.foundries.io
 1. Start the daemon.
    * It should log a “Refreshing target metadata”
    * It should hit errors talking to the server “Unable to update latest metadata”
    * It should sleep 10 seconds and try again
    * Remove the bogus entry from /etc/hosts
    * The next loop of the daemon should succeed in updating the target metadata.

**Pull request merged**
