### PR TITLE
Latest aktualizr

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by mike-sul** [comment]
@pattivacek FYI

**Review by doanac — APPROVED** [review]

**Comment by pattivacek** [comment]
Ah sorry, looks like the change to run clang-tidy on headers means you have some work to do, too. Thankfully it's all pretty easy stuff.

**Comment by mike-sul** [comment]
> Ah sorry, looks like the change to run clang-tidy on headers means you have some work to do, too. Thankfully it's all pretty easy stuff.

NP, sooner or later we will have to do it anyway.

**Comment by mike-sul** [comment]
@pattivacek FYI, I made clang-tidy-11 happy.

**Review by pattivacek — APPROVED** [review]
Great, LGTM!

**Pull request merged**
