### PR TITLE
Added ability to change pkcs11 source file

### PR DESCRIPTION
**Pull request by Hadatko**
needed for arm compilation

Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

### CODE REVIEW

**Comment by mike-sul** [comment]
@Hadatko I suppose we need to wrap it up into `ifdef` statement to enable the auto-detection if `PKCS11_ENGINE_PATH` is not defined.

```
iff --git a/dev-flow.mk b/dev-flow.mk
index 4ed015d..d9f7e58 100644
--- a/dev-flow.mk
+++ b/dev-flow.mk
@@ -12,7 +12,11 @@ GTEST_FILTER ?= "*"
 all: config build
 
 config:
+ifdef ${PKCS11_ENGINE_PATH}
        cmake -S . -B ${BUILD_DIR} -DCMAKE_BUILD_TYPE=Debug -DBUILD_P11=ON -GNinja -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} -DPKCS11_ENGINE_PATH=${PKCS11_ENGINE_PATH}
+else
+       cmake -S . -B ${BUILD_DIR} -DCMAKE_BUILD_TYPE=Debug -DBUILD_P11=ON -GNinja -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC}
+endif

```

**Comment by Hadatko** [comment]
Maybe we can do it more generic?
Something like:
CMAKE_EXTRA_FLAGS ?=
cmake -S . -B ${BUILD_DIR} -DCMAKE_BUILD_TYPE=Debug -DBUILD_P11=ON -GNinja -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} ${CMAKE_EXTRA_FLAGS}
So no ifdef will be necessary?

**Comment by mike-sul** [comment]
> Maybe we can do it more generic?

Makes sense to me.

**Comment by Hadatko** [comment]
Is it ok now?

**Pull request merged**
