### PR TITLE
Adjust to aktualizr changes

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by mike-sul** [comment]
@pattivacek Feel free to pull these changes to your PR https://github.com/foundriesio/aktualizr-lite/pull/150.

**Comment by mike-sul** [comment]
@pattivacek Both the automated and manual tests passes now.

**Comment by pattivacek** [comment]
Anything preventing you from merging this (and then https://github.com/foundriesio/aktualizr-lite/pull/150)? I'd like to use these changes without having to rely on branches. LGTM if I'm allowed to review! :)

**Comment by mike-sul** [comment]
> Anything preventing you from merging this (and then #150)? I'd like to use these changes without having to rely on branches. LGTM if I'm allowed to review! :)

Let @doanac review it too, meanwhile, I'll fix another subtle issue.
You are welcomed to review PRs to this repo, for some reason I can't add you to a list of reviewers, must be some permission issue.

**Comment by doanac** [comment]
LGTM

**Review by pattivacek — APPROVED** [review]

**Pull request merged**
