### PR TITLE
docker: Update golang version of composectl utility

### PR DESCRIPTION
**Pull request by mike-sul**
- Update golang version for `composectl` as well as its dependencies, including docker/moby and containerd in the dev/test container.

- Adjust the docker daemon mock to the golang/composectl version update.

### CODE REVIEW

**Comment by mike-sul** [comment]
@detsch Did you have a chance to review it.

**Review by detsch — DISMISSED** [review]
LGTM

**Comment by detsch** [comment]
> @mike-sul , are the changes in `tests/docker-daemon_fake.py` part of this PR?

Sorry, it is now clear, I'll re-approve the PR.

**Review by detsch — COMMENTED** [review]
LGTM

**Review by detsch — APPROVED** [review]

**Pull request merged**
