### PR TITLE
composeappmanager: Stop Apps just before updating

### PR DESCRIPTION
**Pull request by mike-sul**
It makes sense to stop the apps that are about to be updated just before the ostree installation. If a device unexpectedly turns off immediately after a successful ostree installation but before the apps are updated, then this change ensures that the apps of the previous version are not automatically started upon boot.

### CODE REVIEW

**Review by doanac — COMMENTED** [review]
I think this makes sense, but does this introduce a situation where a customer has a critical compose-app (perhaps it helps drive install logic) that wouldn't start upon the reboot? I guess aklite will still start up and try to do the right thing (if they use aklite)?

**Comment by doanac** [comment]
Might want @Tim-Anderson and @mike-scott to take a look also

**Comment by mike-sul** [comment]
@Tim-Anderson @mike-scott Do you think stopping Apps just before their update is going to break something? 

I think this change shouldn't introduce any regression since `docker compose up` does stop App containers anyway, this change just enforces it slightly earlier, before ostree update.

**Comment by mike-scott** [comment]
@mike-sul I don't see any reason we can't stop disabled compose-apps prior to ostree updates.  @Tim-Anderson what do you think?

**Comment by Tim-Anderson** [comment]
as long as the files are downloaded, I am fine with docker compose down, docker compose up.

**Comment by Tim-Anderson** [comment]
It can still take some time for the copy from reset-apps to docker maybe we should time that

**Comment by mike-sul** [comment]
@doanac Please, approve, I can merge it without at least one approval :).

**Pull request merged**
