### PR TITLE
Improve log messages

### PR DESCRIPTION
**Pull request by mike-sul**
- Log Active Target (short version) at the beginning of each check/update loop
- Log Active Target and New Target diff if they mismatch
- Log Active and New Targets details just before updating to New one

Signed-off-by: Mike Sul <mike.sul@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
I promise I'm not ignoring. I'll take a look on sunday night or monday morning.

**Comment by doanac** [comment]
I'm having a hard time running this. Its actually crashing my rpi3. But there's other problems as well: its trying to install the target 2 times:
~~~
# LD_LIBRARY_PATH=/tmp /tmp/aktualizr-lite daemon
   info: Reading config: "/usr/lib/sota/conf.d/30-rollback.toml"
   info: Reading config: "/usr/lib/sota/conf.d/40-hardware-id.toml"
   info: Reading config: "/var/sota/sota.toml"
   info: Reading config: "/etc/sota/conf.d/z-50-fioctl.toml"
   info: Reading config: "/etc/sota/conf.d/z-90-fiotest.toml"
   info: Use existing SQL storage: "/var/sota/sql.db"
Configuration file wrong or corrupted
warning: Failed resetting bootcount
Configuration file wrong or corrupted
warning: Failed resetting upgrade_available for u-boot
   info: Active Target: raspberrypi3-64-lmp-90, sha256: 668e20b088c0d08529b67652a49f746673d963d6803edac86126fc0aa3a366fc
   info: Checking for a new Target...
OK
OK
   info: Got a New Target ! 
   info: Updating Active Target: 90	sha256:668e20b088c0d08529b67652a49f746673d963d6803edac86126fc0aa3a366fc
   info: 	Docker Compose Apps:
   info: 	on: fiotest -> hub.foundries.io/andy-corp/fiotest@sha256:10e201479442b6593cab5616ed88ffc507f9090d6da83a062dabdeccfa70271b
   info: 	off: helloworld -> hub.foundries.io/andy-corp/helloworld@sha256:1cc24ec1e6ddf804b2e212bf352a9ab37ff57842ba81e3d3be3049f5ca7e0eb4
   info: 	off: homeassistant -> hub.foundries.io/andy-corp/homeassistant@sha256:5a61cae9691f074f028c72e9f68cfd18d50200a2c54f1667cc8a8134c4bdc33a
   info: 	off: homelab -> hub.foundries.io/andy-corp/homelab@sha256:5875955410ae3770fcb0d5b613140cdf87a8c0e438d1b3dd69f94b06ddf33401
   info: 	on: shellhttpd -> hub.foundries.io/andy-corp/shellhttpd@sha256:2f61a894f952b03628dd00b9cb817ba40ba25ed4ac9291c9c560e3f3a33e0c92
   info: To New Target: 90	sha256:668e20b088c0d08529b67652a49f746673d963d6803edac86126fc0aa3a366fc
   info: 	Docker Compose Apps:
   info: 	on: fiotest -> hub.foundries.io/andy-corp/fiotest@sha256:a1aac06fcfa467e5b111a0e42fbc5d63b3746968cc14aca4323a86915f62acf2
   info: 	off: helloworld -> hub.foundries.io/andy-corp/helloworld@sha256:c7e1085b621f907ec38631ab475a9b4fbabc43ae0d03bffda8ac35790c193979
   info: 	off: homeassistant -> hub.foundries.io/andy-corp/homeassistant@sha256:87d5c4e0e1b5eaf7165ac8cf226c9453aeec0d294d1a9a70fea8b6da6dba0641
   info: 	off: homelab -> hub.foundries.io/andy-corp/homelab@sha256:eae2d779be616ee36afccd51a8fa6eb42605fba6b11f6f6abb2caf3d3f8d1de4
   info: 	on: shellhttpd -> hub.foundries.io/andy-corp/shellhttpd@sha256:c69971be4d2f94f0712358ed5f29a7a9e809fa49c82370ac573d3a5fa0046671
OK
   info: Looking for Compose Apps to be installed or updated...
   info: fiotest will be updated
   info: shellhttpd will be updated
   info: Found 2 Apps to update
   info: Fetching fiotest -> hub.foundries.io/andy-corp/fiotest@sha256:a1aac06fcfa467e5b111a0e42fbc5d63b3746968cc14aca4323a86915f62acf2
   info: Validating compose file
services:
  fiotest:
    command: python3 -m fiotest.main /test-spec.yml
    image: hub.foundries.io/lmp/fiotest@sha256:8169487d6dd78c63c05d8983218e615012a70775dd6edfe62248a0b77ad0ff30
    ports:
    - published: 8000
      target: 8000
    privileged: true
    restart: always
    volumes:
    - /etc/sota/conf.d:/etc/sota/conf.d:rw
    - /var/sota:/var/sota:rw
    - /var/sota/compose/fiotest/test-spec.yml:/test-spec.yml:rw
    - /var/lib/fiotest:/var/lib/fiotest:rw
version: '3.5'

   info: Pulling containers
Pulling fiotest (hub.foundries.io/lmp/fiotest@sha256:8169487d6dd78c63c05d8983218e615012a70775dd6edfe62248a0b77ad0ff30)...
sha256:8169487d6dd78c63c05d8983218e615012a70775dd6edfe62248a0b77ad0ff30: Pulling from lmp/fiotest
Digest: sha256:8169487d6dd78c63c05d8983218e615012a70775dd6edfe62248a0b77ad0ff30
Status: Image is up to date for hub.foundries.io/lmp/fiotest@sha256:8169487d6dd78c63c05d8983218e615012a70775dd6edfe62248a0b77ad0ff30
   info: Fetching shellhttpd -> hub.foundries.io/andy-corp/shellhttpd@sha256:c69971be4d2f94f0712358ed5f29a7a9e809fa49c82370ac573d3a5fa0046671
   info: Validating compose file
services:
  httpd:
    environment:
      MSG: Hello world
    image: hub.foundries.io/andy-corp/shellhttpd@sha256:a426ba338722c89048effebb97a1d3370f05bd9de229dda54297972f818b21e5
    ports:
    - published: 8080
      target: 8080
    restart: always
version: '3.2'

   info: Pulling containers
Pulling httpd (hub.foundries.io/andy-corp/shellhttpd@sha256:a426ba338722c89048effebb97a1d3370f05bd9de229dda54297972f818b21e5)...
sha256:a426ba338722c89048effebb97a1d3370f05bd9de229dda54297972f818b21e5: Pulling from andy-corp/shellhttpd
Digest: sha256:a426ba338722c89048effebb97a1d3370f05bd9de229dda54297972f818b21e5
Status: Image is up to date for hub.foundries.io/andy-corp/shellhttpd@sha256:a426ba338722c89048effebb97a1d3370f05bd9de229dda54297972f818b21e5
OK
OK
   info: Installing package using ostree+compose_apps package manager
   info: Target 668e20b088c0d08529b67652a49f746673d963d6803edac86126fc0aa3a366fc is same as current
   info: Installing fiotest -> hub.foundries.io/andy-corp/fiotest@sha256:a1aac06fcfa467e5b111a0e42fbc5d63b3746968cc14aca4323a86915f62acf2
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

fiotest_fiotest_1 is up-to-date
   info: Installing shellhttpd -> hub.foundries.io/andy-corp/shellhttpd@sha256:c69971be4d2f94f0712358ed5f29a7a9e809fa49c82370ac573d3a5fa0046671
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

shellhttpd_httpd_1 is up-to-date
   info: Pruning unused docker images
Total reclaimed space: 0B
   info: Update complete. No reboot needed
OK
   info: Active Target: raspberrypi3-64-lmp-90, sha256: 668e20b088c0d08529b67652a49f746673d963d6803edac86126fc0aa3a366fc
   info: Checking for a new Target...
OK
OK
   info: Got a New Target ! 
   info: Updating Active Target: 90	sha256:668e20b088c0d08529b67652a49f746673d963d6803edac86126fc0aa3a366fc
   info: 	Docker Compose Apps:
   info: 	on: fiotest -> hub.foundries.io/andy-corp/fiotest@sha256:10e201479442b6593cab5616ed88ffc507f9090d6da83a062dabdeccfa70271b
   info: 	off: helloworld -> hub.foundries.io/andy-corp/helloworld@sha256:1cc24ec1e6ddf804b2e212bf352a9ab37ff57842ba81e3d3be3049f5ca7e0eb4
   info: 	off: homeassistant -> hub.foundries.io/andy-corp/homeassistant@sha256:5a61cae9691f074f028c72e9f68cfd18d50200a2c54f1667cc8a8134c4bdc33a
   info: 	off: homelab -> hub.foundries.io/andy-corp/homelab@sha256:5875955410ae3770fcb0d5b613140cdf87a8c0e438d1b3dd69f94b06ddf33401
   info: 	on: shellhttpd -> hub.foundries.io/andy-corp/shellhttpd@sha256:2f61a894f952b03628dd00b9cb817ba40ba25ed4ac9291c9c560e3f3a33e0c92
   info: To New Target: 90	sha256:668e20b088c0d08529b67652a49f746673d963d6803edac86126fc0aa3a366fc
   info: 	Docker Compose Apps:
   info: 	on: fiotest -> hub.foundries.io/andy-corp/fiotest@sha256:a1aac06fcfa467e5b111a0e42fbc5d63b3746968cc14aca4323a86915f62acf2
   info: 	off: helloworld -> hub.foundries.io/andy-corp/helloworld@sha256:c7e1085b621f907ec38631ab475a9b4fbabc43ae0d03bffda8ac35790c193979
   info: 	off: homeassistant -> hub.foundries.io/andy-corp/homeassistant@sha256:87d5c4e0e1b5eaf7165ac8cf226c9453aeec0d294d1a9a70fea8b6da6dba0641
   info: 	off: homelab -> hub.foundries.io/andy-corp/homelab@sha256:eae2d779be616ee36afccd51a8fa6eb42605fba6b11f6f6abb2caf3d3f8d1de4
   info: 	on: shellhttpd -> hub.foundries.io/andy-corp/shellhttpd@sha256:c69971be4d2f94f0712358ed5f29a7a9e809fa49c82370ac573d3a5fa0046671
OK
   info: Looking for Compose Apps to be installed or updated...
   info: fiotest will be updated
   info: shellhttpd will be updated
   info: Found 2 Apps to update
   info: Fetching fiotest -> hub.foundries.io/andy-corp/fiotest@sha256:a1aac06fcfa467e5b111a0e42fbc5d63b3746968cc14aca4323a86915f62acf2
   info: Validating compose file
client_loop: send disconnect: Broken pipe
~~~

Looks like it doesn't think the compose apps are running and then it crashes each time when it tries to validate my compose file the 2nd time.

**Comment by mike-sul** [comment]
> Looks like it doesn't think the compose apps are running and then it crashes each time when it tries to validate my compose file the 2nd time.

Wow, what's happening here, really odd logs.
"Configuration file wrong or corrupted"
"WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`."

**Comment by doanac** [comment]
this is working okay now. my fiotest app was rebooting the device and causing havoc.

**Comment by mike-sul** [comment]
> this is working okay now. my fiotest app was rebooting the device and causing havoc.

I double-checked this PR on my RPi, seems fine to me.

However, there is a tiny issue with `dockerAppsChanged()` called on the first loop of the daemon mode - if one or more apps from the list of apps in the config are not present in Active nor New Target aklite treats it as `Config change detected: list of apps has changed`. It happens because `dockerAppsChanged()` compares the app list from sota.toml with what is installed under compose-apps neglecting the list of apps specified in Target. Obviously, there are no apps under compose-apps directory that are not listed in Target while such apps can be specified in the sota.toml hence mismatch.

**Comment by mike-sul** [comment]
@doanac Added a fix for dockerAppsChanged().

**Comment by mike-sul** [comment]
@doanac Can I merge it?

**Pull request merged**
