### PR TITLE
Latest aktualizr

### PR DESCRIPTION
**Pull request by pattivacek**

### CODE REVIEW

**Comment by mike-sul** [comment]
@pattivacek The changes LGTM, thanks for doing it.
The only comment is that we would like to make aktualizr-lite dependent on "foundriesio/aktualizr" not "uptane/aktualizr" so we can easily and quickly apply any patch to aktualizr if needed. Therefore, I created I new PR https://github.com/foundriesio/aktualizr-lite/pull/139 which is copy of the given one except that it points to "foundriesio/aktualizr" (https://github.com/foundriesio/aktualizr/tree/2021.11%2Bfio). It's a copy/fork of https://github.com/uptane/aktualizr/tree/foundries-rebased plus this commit https://github.com/uptane/aktualizr/pull/39/commits/4d047ccee6398cf14dbf54d5c3505400410e8775.

**Comment by pattivacek** [comment]
> The only comment is that we would like to make aktualizr-lite dependent on "foundriesio/aktualizr" not "uptane/aktualizr" so we can easily and quickly apply any patch to aktualizr if needed.

Sure, sounds fine! I'd suggest waiting for https://github.com/uptane/aktualizr/pull/39 to get merged so we can update appropriately, but then it should be good to go.

**Comment by mike-sul** [comment]
> I'd suggest waiting for [uptane/aktualizr#39](https://github.com/uptane/aktualizr/pull/39) to get merged so we can update appropriately, but then it should be good to go.

Cool, thanks.

**Comment by pattivacek** [comment]
Closed since it's been replaced by https://github.com/foundriesio/aktualizr-lite/pull/139.

**Pull request closed without merging**
