### PR TITLE
Cleanup documentation in aktualizr-lite

### PR DESCRIPTION
**Pull request by kprosise**
Fixed a typo in `how-to-run-locally.md`, cleaned up section headers, and applied style guide rules when sensible. Linted for style and markdown best practices.

QA: ran vale linter with fio-style rules.

No Jira issues to link.

### CODE REVIEW

**Review by mike-sul — APPROVED** [review]

**Comment by mike-sul** [comment]
@kprosise Please, create a new PR for a branch created within foundriesio/aktualizr-lite repo. Currently, the CI jobs won't run for branches created outside of `foundriesio/aktualizr-lite repo` and it blocks merging.

**Comment by kprosise** [comment]
Will do!

**Comment by kprosise** [comment]
@mike-sul I do not have permission to create a branch, as suspected.

**Comment by mike-sul** [comment]
> @mike-sul I do not have permission to create a branch, as suspected.

Please, try now

**Pull request closed without merging**
