### PR TITLE
aktualizr: switch to 2020.10+fio

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike Sul <mike.sul@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
are there any changes of note between 2020.9 and 2020.10?

**Comment by mike-sul** [comment]
> are there any changes of note between 2020.9 and 2020.10?

Well, IMHO, nothing important that's why I didn't put any notes. Changes are mostly related to improving code quality, some cleanups, comment/logs/exception wording improvement, etc. The only thing that maybe is worth mentioning is that they pull in 2020.10 some of yours and my fixes to aktualizr, I will update the commit correspondingly.

**Comment by mike-sul** [comment]
Relevant changes:
- c841de152 aktualizr-get: fix the issue with param check
- c79f9d65b aktualizr-get: Allow passing HTTP headers
- 0718650c5 Remove aktualizr-lite
- d9abc9fc8 packagemanage: Fix output of pacman config
- 4ef5ba1c0 support new backend authentication for garage-push and garage-deploy (backward compatible)

**Comment by mike-sul** [comment]
Tested on a device, LGTM.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by doanac** [comment]
yep. nothing interesting. ironically the interesting bits to me where things I'd forgotten that i'd pushed upstream :)

**Review by doanac — APPROVED** [review]

**Pull request merged**
